<?php
/**
 * EasyMage ProductGift
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so you can be sent a copy immediately.
 *
 * Original code copyright (c) 2006-2016 X.commerce, Inc. (http://www.magento.com)
 *
 * @package    EasyMage ProductGift
 * @author     Konstantin Dubovik
 * @contact    kodubovik@gmail.com
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * Product gift config form template
 *
 * @see EasyMage_ProductGift_Block_Adminhtml_Productgift_Edit_Form
 */
?>
<div id="edit_form_wrap" class="entity-edit">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4><?php echo $this->__('Manage productgift categories')?></h4>
        </div>
    </div>
    <form id="edit_form" method="post" action="<?php echo $this->getSaveUrl() ?>">
        <input name="form_key" type="hidden" value="<?php echo $this->getFormKey()?>" />
        <input name="store" type="hidden" value="<?php echo Mage::helper('easymage_productgift')->getSelectedStore(); ?>" />
        <?php echo $this->getChildHtml('store_switcher'); ?>
        <div class="box">
            <div class="hor-scroll">
                <table cellspacing="0" cellpadding="0" class="dynamic-grid" style="width:100%;" align="center">
                    <thead>
                    <tr class="headings">
                        <th style="width:20%;"><?php echo $this->__('Product category')?></th>
                        <th style="width:20%;"><?php echo $this->__('Gift product SKU')?></th>
                        <th style="width:5%;">&nbsp;</th>
                        <th style="width:5%;">&nbsp;</th>
                        <th style="width:5%;">&nbsp;</th>
                        <th style="width:45%;">&nbsp;</th>
                    </tr>
                    </thead>
                    <tbody id="mapping-table-body">
                    <?php echo $this->getTableBodyHtml() ?>
                    </tbody>
                </table>
                </br>
                <button id="add_row_btn" onclick="addRow();return false;" class="scalable add" title="Add Row">
                    <span><?php echo $this->__('Add Row')?></span>
                </button>
            </div>
        </div>
    </form>

    <script type="text/javascript">
        var lastIndex = getLastIndex();

        function removeRow(index) {
            var currentRow = $('table-row-' + index);
            var currentSelects = $$('#table-row-' + index + ' .required-entry');
            for(i = 0; i < currentSelects.length; i ++){
                currentSelects[i].setAttribute('disabled', 'disabled');
            }
            currentRow.hide();
        }

        function addRow()
        {
            var indexTAppend = lastIndex + 1;
            var rowHtml = '<tr id="table-row-' + indexTAppend + '" class="table-row-productgift">';
            rowHtml += '<td style="display:none;"><input type="hidden" name="apply-status[' + indexTAppend + ']" value="0"/></td>';
            rowHtml += '<td><select name="category-select[' + indexTAppend + ']" class="required-entry select-category">';
            rowHtml += '<?php echo $this->getOptionsHtml()?>';
            rowHtml += '</select></td>';
            rowHtml += '<td><input style="width:50%;" name="gift-sku[' + indexTAppend + ']" class="required-entry"/></td>';
            rowHtml += '<td><button type="button" onclick="removeRow(' + indexTAppend + ');" class="delete delete-option">Remove Row</button></td>';
            var lastRowId = "table-row-" + lastIndex;
            var elementToAppend = $(lastRowId);
            if(elementToAppend != null)
            {
                $(lastRowId).insert({after:rowHtml});
                lastIndex++;
            }
        }
        function getLastIndex()
        {
            return $('mapping-table-body').getElementsByTagName("tr").length - 1;
        }

    </script>
</div>
<style>
    span.disabled {
        display: block;
        position: absolute;
        width: 100%;
        height: 100%;
        top: 0;
        background: rgba(255,255,255,.5);
    }
    a.form-button {
        color: #fff !important;
        text-decoration: none !important;
    }
    a.form-button:hover {
        background: #f77c16;
    }
</style>